### ISSUE TITLE
Issue with reading the file in FillablePDF outside console

### ISSUE THREAD

**Issue by hmxa22** [vkononov/fillable-pdf#20]
File not found as file or resource. (input file may be corrupt, incompatible, or may not have any forms)
I am receiving the above mentioned error when doing FillablePDF.new(path) inside my models or controllers, however it seems to work fine when I do it from rails console.

**Comment by vkononov** [comment]
I assume you're using version [0.9.2](https://github.com/vkononov/fillable-pdf/releases/tag/v0.9.2) of the gem? If so, would you be able to send me the file? It would really help me with debugging.

**Comment by hmxa22** [comment]
Im using version 0.9.1 of the gem. I have also sent you the file on you mail. Thanks for quick response.

**Comment by vkononov** [comment]
@hmxa22 Please use the [0.9.2](https://github.com/vkononov/fillable-pdf/releases/tag/v0.9.2) version of the gem. There was an issue that I fixed:

`Fixed an issue that caused an IllegalArgumentException when passing an instance of Pathname instead of a string to FillablePDF.new.`

Upgrading to the latest version will most likely resolve your issue. If it doesn't, please post some code that I can see how you're passing the file path to the gem.
