### ISSUE TITLE
Missing national characters

### ISSUE THREAD

**Issue by tfader** [vkononov/fillable-pdf#23]
Any idea what I'm doing wrong or what should I change?

In any fields with value included national characters, proper value is displayed only when field is "clicked/active"

In printout or preview national characters are invisible.

Working OKey only when I input manually (from Adobe Reader or macOs preview) values with national characters.

The issue is only when I fill form from RoR application (UTF-8 as default for app and DB).

Examples as attached.

<img width="747" alt="Zrzut ekranu 2022-07-7 o 14 48 02" src="https://user-images.githubusercontent.com/22178012/177779095-9aa40b7d-5197-47b5-98c1-0c5d42e8bc0a.png">
<img width="266" alt="Zrzut ekranu 2022-07-7 o 14 51 00" src="https://user-images.githubusercontent.com/22178012/177779126-7aabd2fd-ad94-4d2e-8426-8a3d3da6b092.png">

**Comment by vkononov** [comment]
Unfortunately the fix to add `false` as a second parameter of `setValue` does not work with the latest iText version (7.2.3). The problem is likely with the encoding of the original PDF file, and the encoding of the font you're using in that form field probably does not support these types of characters.

**Comment by vkononov** [comment]
There is now a `generate_appearance` optional parameter for the `set_field` and `set_fields` methods that partially addresses this problem.

**Comment by tfader** [comment]
Thank you for this change. Now it's OK.
